// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTfBfhSUkEU0RoR7gs4J8TsNJnvu6CGO4',
    appId: '1:702843016698:web:e4d61880d00faaa5318043',
    messagingSenderId: '702843016698',
    projectId: 'verbalautism-e8776',
    authDomain: 'verbalautism-e8776.firebaseapp.com',
    storageBucket: 'verbalautism-e8776.appspot.com',
    measurementId: 'G-Y2MT2F2D69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXZJcK6dBXVJg0z-cinXmiXYzX703x-f8',
    appId: '1:702843016698:android:3048e8c369a6969e318043',
    messagingSenderId: '702843016698',
    projectId: 'verbalautism-e8776',
    storageBucket: 'verbalautism-e8776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyy3ijiiHc8U1if9usfQEHCAC6F83MhXg',
    appId: '1:702843016698:ios:d92b83fddff8a0c5318043',
    messagingSenderId: '702843016698',
    projectId: 'verbalautism-e8776',
    storageBucket: 'verbalautism-e8776.appspot.com',
    iosBundleId: 'com.example.verbalautism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyy3ijiiHc8U1if9usfQEHCAC6F83MhXg',
    appId: '1:702843016698:ios:d92b83fddff8a0c5318043',
    messagingSenderId: '702843016698',
    projectId: 'verbalautism-e8776',
    storageBucket: 'verbalautism-e8776.appspot.com',
    iosBundleId: 'com.example.verbalautism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTfBfhSUkEU0RoR7gs4J8TsNJnvu6CGO4',
    appId: '1:702843016698:web:fd05b2d4e55e14cd318043',
    messagingSenderId: '702843016698',
    projectId: 'verbalautism-e8776',
    authDomain: 'verbalautism-e8776.firebaseapp.com',
    storageBucket: 'verbalautism-e8776.appspot.com',
    measurementId: 'G-FRBLW9D0QJ',
  );
}
